"""Sample ShipStation-like orders for demo mode (no API keys)."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from .models import Shipment


def sample_shipments() -> list[Shipment]:
    now = datetime.now(timezone.utc)
    return [
        Shipment(
            order_id="1001",
            order_number="MB-10421",
            status="shipped",
            carrier="UPS",
            service="UPS Ground",
            tracking_number="1Z999AA10123456784",
            tracking_url="https://www.ups.com/track?tracknum=1Z999AA10123456784",
            ship_date=(now - timedelta(days=1)).date().isoformat(),
            estimated_delivery=(now + timedelta(days=2)).date().isoformat(),
            customer_name="Maria Soto",
            customer_email="maria.soto@gulfcoastdistribution.com",
            ship_to_city="Houston",
            ship_to_state="TX",
            ship_to_country="US",
            items_summary="2x Agent Pilot Kit",
        ),
        Shipment(
            order_id="1002",
            order_number="MB-10418",
            status="exception",
            carrier="FedEx",
            service="FedEx Home Delivery",
            tracking_number="794612345678",
            tracking_url="https://www.fedex.com/fedextrack/?trknbr=794612345678",
            ship_date=(now - timedelta(days=5)).date().isoformat(),
            estimated_delivery=(now - timedelta(days=1)).date().isoformat(),
            customer_name="Jake Nguyen",
            customer_email="jake@quickhvac.biz",
            ship_to_city="Katy",
            ship_to_state="TX",
            ship_to_country="US",
            items_summary="1x Sensor pack",
            raw={"statusDetail": "Delivery exception — recipient not available"},
        ),
        Shipment(
            order_id="1003",
            order_number="MB-10405",
            status="shipped",
            carrier="USPS",
            service="Priority Mail",
            tracking_number="9400111899223344556677",
            tracking_url="https://tools.usps.com/go/TrackConfirmAction?tLabels=9400111899223344556677",
            ship_date=(now - timedelta(days=6)).date().isoformat(),
            estimated_delivery=(now - timedelta(days=2)).date().isoformat(),
            customer_name="Priya Shah",
            customer_email="ops@transocean-freight.com",
            ship_to_city="Houston",
            ship_to_state="TX",
            ship_to_country="US",
            items_summary="Docs kit",
            raw={"statusDetail": "In transit — delayed"},
        ),
        Shipment(
            order_id="1004",
            order_number="MB-10430",
            status="awaiting_shipment",
            carrier="",
            service="",
            tracking_number="",
            ship_date="",
            estimated_delivery="",
            customer_name="Sam Bloggs",
            customer_email="info@randomblog.net",
            ship_to_city="Austin",
            ship_to_state="TX",
            ship_to_country="US",
            items_summary="1x Starter box",
        ),
        Shipment(
            order_id="1005",
            order_number="MB-10390",
            status="delivered",
            carrier="UPS",
            service="UPS Ground",
            tracking_number="1Z999AA10987654321",
            tracking_url="https://www.ups.com/track?tracknum=1Z999AA10987654321",
            ship_date=(now - timedelta(days=8)).date().isoformat(),
            estimated_delivery=(now - timedelta(days=4)).date().isoformat(),
            customer_name="Anwar Chowdhury",
            customer_email="anwar.chowdhury@matrixbazaar.com",
            ship_to_city="Houston",
            ship_to_state="TX",
            ship_to_country="US",
            items_summary="Internal sample",
        ),
    ]
