"""Assemble a full custom FastAPI agent package from graph modules + profile."""

from __future__ import annotations

import json
from typing import Any


def assemble_package_files(
    *,
    profile: dict[str, Any],
    architecture: dict[str, Any],
    modules: dict[str, dict[str, Any]],
) -> dict[str, str]:
    """Return relative_path → file content for the bespoke agent package."""
    name = profile.get("business_name") or "Custom Business"
    pkg = architecture.get("package_name") or "seo-agent-custom"
    slug = architecture.get("package_slug") or "custom"
    port = int(architecture.get("port") or 8801)
    areas = profile.get("service_areas") or []
    goal = profile.get("primary_goal") or "organic_leads"
    niche = profile.get("niche") or profile.get("industry") or "services"
    website = profile.get("website") or ""
    seeds = profile.get("seed_keywords") or []
    safety = profile.get("safety_rules") or []
    profile_id = profile.get("id") or ""

    voice_md = (modules.get("brand") or {}).get("voice_md") or (
        f"# Brand Voice — {name}\n\nPlain English. Never invent stats, reviews, or rankings.\n"
    )

    files: dict[str, str] = {}

    # Module source files
    for key, mod in modules.items():
        path = mod.get("path")
        code = mod.get("code")
        if path and code:
            files[path] = code

    files["brand/voice.md"] = voice_md
    files["profile/business_seo_profile.json"] = json.dumps(profile, indent=2, ensure_ascii=False)
    if profile.get("summary_markdown"):
        files["profile/business_seo_profile.md"] = profile["summary_markdown"]

    files["config.yaml"] = _config_yaml(
        name=name,
        website=website,
        niche=niche,
        areas=areas,
        goal=goal,
        port=port,
        profile_id=profile_id,
        seeds=seeds,
    )
    files[".env.example"] = (
        f"# {name} — bespoke SEO agent\n"
        "XAI_API_KEY=\n"
        f"AGENT_PORT={port}\n"
        "HITL_AUTO_APPROVE=false\n"
        f"BUSINESS_NAME={name}\n"
    )
    files["requirements.txt"] = (
        "fastapi>=0.115.0\n"
        "uvicorn[standard]>=0.32.0\n"
        "pydantic>=2.9.0\n"
        "python-dotenv>=1.0.1\n"
        "pyyaml>=6.0.2\n"
        "httpx>=0.28.0\n"
        "rich>=13.9.0\n"
    )
    files["agent/__init__.py"] = f'"""Bespoke SEO agent for {name}."""\n\n__version__ = "1.0.0"\n'
    files["agent/modules/__init__.py"] = '"""Specialized modules generated for this business."""\n'
    files["agent/config.py"] = _agent_config_py()
    files["agent/models.py"] = _agent_models_py(name)
    files["agent/main.py"] = _agent_main_py(name, port)
    files["agent/cli.py"] = _agent_cli_py(name, port)
    files["agent/agent.py"] = _agent_core_py(name, niche, goal, areas)
    files["scripts/smoke_test.py"] = _smoke_py(name)
    files["README.md"] = _readme_md(name, pkg, port, niche, goal, areas)
    files["data/.gitkeep"] = ""

    # Architecture note for owners
    files["ARCHITECTURE.md"] = (
        f"# Architecture — {name}\n\n"
        f"Package: `{pkg}` (slug: `{slug}`)\n\n"
        "This agent was generated by **Matrixly SEO-Bespoke** from your Business SEO Profile.\n\n"
        "## Modules\n\n"
        + "\n".join(
            f"- **{m.get('id')}**: `{m.get('path')}` — exports: {', '.join(m.get('exports') or [])}"
            for m in modules.values()
            if m
        )
        + "\n\n## Safety\n\n"
        + "\n".join(f"- {r}" for r in safety)
        + "\n\n## HITL\n\n"
        "Publishing actions require human approval. Never auto-publish customer-facing content.\n"
    )

    return files


def _config_yaml(
    *,
    name: str,
    website: str,
    niche: str,
    areas: list[str],
    goal: str,
    port: int,
    profile_id: str,
    seeds: list[dict],
) -> str:
    areas_yaml = "\n".join(f'  - "{a}"' for a in areas) or '  - ""'
    seed_lines = []
    for s in seeds[:12]:
        kw = str(s.get("keyword") or "").replace('"', '\\"')
        intent = str(s.get("intent") or "local")
        seed_lines.append(f'  - keyword: "{kw}"\n    intent: "{intent}"')
    seeds_yaml = "\n".join(seed_lines) if seed_lines else "  []"
    return f"""# Bespoke SEO agent config — {name}
# Generated by Matrixly SEO-Bespoke. Edit freely; re-run quiz to regenerate.

business:
  name: "{name}"
  website: "{website}"
  niche: "{niche}"
  primary_goal: "{goal}"
  profile_id: "{profile_id}"
  service_areas:
{areas_yaml}

seo:
  require_hitl_before_publish: true
  never_invent:
    - statistics
    - reviews
    - rankings
    - guarantees

seed_keywords:
{seeds_yaml}

server:
  host: "0.0.0.0"
  port: {port}

hitl:
  mode: external_only
"""


def _agent_config_py() -> str:
    return '''"""Load config for the bespoke agent."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent


def load_config() -> dict[str, Any]:
    load_dotenv(ROOT / ".env")
    raw: dict[str, Any] = {}
    cfg_path = ROOT / "config.yaml"
    if cfg_path.exists():
        with cfg_path.open(encoding="utf-8") as f:
            raw = yaml.safe_load(f) or {}
    raw.setdefault("paths", {})["root"] = str(ROOT)
    raw.setdefault("paths", {})["data"] = str(ROOT / "data")
    (ROOT / "data").mkdir(parents=True, exist_ok=True)
    xai = raw.setdefault("xai", {})
    xai["api_key"] = os.getenv("XAI_API_KEY") or xai.get("api_key")
    return raw
'''


def _agent_models_py(name: str) -> str:
    return f'''"""Models for {name} bespoke SEO agent."""

from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field


class PlanRequest(BaseModel):
    goal: str = "organic_leads"
    notes: str = ""


class ContentRequest(BaseModel):
    content_type: str = "service_page"
    topic: str = ""
    primary_keyword: str = ""


class RankUpdate(BaseModel):
    keyword: str
    rank: Optional[int] = None


class RoiRecord(BaseModel):
    hours_saved: float = 0.0
    leads_attributed: int = 0
    revenue_usd: float = 0.0
    note: str = ""
'''


def _agent_core_py(name: str, niche: str, goal: str, areas: list[str]) -> str:
    return f'''"""Core orchestrator for {name}."""

from __future__ import annotations

from typing import Any

from .modules.brand_voice import get_voice, inject_system_preamble, render_voice_md
from .modules.content_engine import content_brief, draft_markdown
from .modules.keyword_tracker import KeywordTracker
from .modules.local_seo import local_checklist, location_page_outline, review_response_templates
from .modules.research_planner import plan_research, prioritize
from .modules.roi_cards import RoiCards


class BespokeSeoAgent:
    """Custom SEO agent specialized for {name} ({niche})."""

    def __init__(self, cfg: dict[str, Any]) -> None:
        self.cfg = cfg
        data = cfg.get("paths", {{}}).get("data") or "data"
        self.tracker = KeywordTracker(f"{{data}}/keywords.json")
        self.roi = RoiCards(f"{{data}}/roi.json")
        self.business_name = {name!r}
        self.niche = {niche!r}
        self.default_goal = {goal!r}
        self.service_areas = {areas!r}

    def status(self) -> dict[str, Any]:
        return {{
            "service": "bespoke-seo-agent",
            "business": self.business_name,
            "niche": self.niche,
            "goal": self.default_goal,
            "service_areas": self.service_areas,
            "keywords": self.tracker.summary(),
            "roi": self.roi.cards(),
            "voice": get_voice().get("business_name"),
            "safety": "HITL required; never invent stats/reviews/rankings",
        }}

    def research_plan(self, goal: str | None = None) -> dict[str, Any]:
        plan = plan_research(goal or self.default_goal)
        plan["prioritized"] = prioritize(plan.get("topics"))
        plan["system_preamble"] = inject_system_preamble()
        return plan

    def local_package(self) -> dict[str, Any]:
        areas = self.service_areas or []
        outlines = [location_page_outline(a) for a in areas[:5]]
        return {{
            "checklist": local_checklist(),
            "review_templates": review_response_templates(),
            "location_outlines": outlines,
        }}

    def content_package(
        self,
        content_type: str = "service_page",
        topic: str = "",
        primary_keyword: str = "",
    ) -> dict[str, Any]:
        brief = content_brief(content_type, topic, primary_keyword)
        draft = draft_markdown(brief)
        return {{
            "brief": brief,
            "draft_markdown": draft,
            "status": "pending_review",
            "note": "Human approval required before publish.",
            "voice": render_voice_md()[:500],
        }}

    def record_roi(self, **kwargs: Any) -> dict[str, Any]:
        return self.roi.record(**kwargs)
'''


def _agent_main_py(name: str, port: int) -> str:
    return f'''"""FastAPI app for {name} bespoke SEO agent."""

from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .agent import BespokeSeoAgent
from .config import load_config
from .models import ContentRequest, PlanRequest, RankUpdate, RoiRecord

cfg = load_config()
agent = BespokeSeoAgent(cfg)

app = FastAPI(
    title="{name} SEO Agent",
    description="Bespoke SEO agent generated by Matrixly SEO-Bespoke",
    version="1.0.0",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/v1/health")
def health():
    st = agent.status()
    return {{"ok": True, "service": "bespoke-seo-agent", "business": st.get("business"), **{{k: st[k] for k in ("niche", "keywords", "roi") if k in st}}}}


@app.get("/v1/status")
def status():
    return agent.status()


@app.post("/v1/research")
def research(body: PlanRequest):
    return agent.research_plan(body.goal)


@app.post("/v1/local")
def local():
    return agent.local_package()


@app.post("/v1/content")
def content(body: ContentRequest):
    return agent.content_package(body.content_type, body.topic, body.primary_keyword)


@app.get("/v1/keywords")
def keywords():
    return {{"items": agent.tracker.list(), "summary": agent.tracker.summary()}}


@app.post("/v1/keywords/rank")
def set_rank(body: RankUpdate):
    return agent.tracker.set_rank(body.keyword, body.rank)


@app.get("/v1/roi")
def roi():
    return agent.roi.cards()


@app.post("/v1/roi")
def roi_record(body: RoiRecord):
    return agent.record_roi(
        hours_saved=body.hours_saved,
        leads_attributed=body.leads_attributed,
        revenue_usd=body.revenue_usd,
        note=body.note,
    )
'''


def _agent_cli_py(name: str, port: int) -> str:
    return f'''"""CLI for {name} bespoke SEO agent."""

from __future__ import annotations

import argparse
import json

from rich.console import Console
from rich.panel import Panel

from .agent import BespokeSeoAgent
from .config import load_config

console = Console()


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="bespoke-seo")
    p.add_argument(
        "command",
        choices=["status", "research", "local", "content", "keywords", "roi", "serve"],
    )
    p.add_argument("--topic", default="")
    p.add_argument("--type", dest="content_type", default="service_page")
    p.add_argument("--host", default="0.0.0.0")
    p.add_argument("--port", type=int, default={port})
    p.add_argument("--json", action="store_true")
    args = p.parse_args(argv)

    cfg = load_config()
    agent = BespokeSeoAgent(cfg)

    if args.command == "status":
        st = agent.status()
        print(json.dumps(st, indent=2) if args.json else Panel.fit(json.dumps(st, indent=2), title="{name}"))
        return 0
    if args.command == "research":
        print(json.dumps(agent.research_plan(), indent=2))
        return 0
    if args.command == "local":
        print(json.dumps(agent.local_package(), indent=2))
        return 0
    if args.command == "content":
        print(json.dumps(agent.content_package(args.content_type, args.topic), indent=2))
        return 0
    if args.command == "keywords":
        print(json.dumps(agent.tracker.summary(), indent=2))
        return 0
    if args.command == "roi":
        print(json.dumps(agent.roi.cards(), indent=2))
        return 0
    if args.command == "serve":
        import uvicorn
        console.print(f"[green]Serving {name} bespoke agent on http://{{args.host}}:{{args.port}}[/green]")
        uvicorn.run("agent.main:app", host=args.host, port=args.port, reload=False)
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _smoke_py(name: str) -> str:
    return f'''#!/usr/bin/env python3
"""Smoke test for {name} bespoke SEO agent (no API key required)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agent.config import load_config
from agent.agent import BespokeSeoAgent


def main() -> int:
    cfg = load_config()
    agent = BespokeSeoAgent(cfg)
    st = agent.status()
    assert st.get("business"), "business missing"
    plan = agent.research_plan()
    assert plan.get("topics") is not None
    local = agent.local_package()
    assert local.get("checklist")
    content = agent.content_package(topic="core service")
    assert content.get("draft_markdown")
    assert "pending_review" in str(content.get("status"))
    # Ensure draft does not invent review stars
    assert "5-star" not in content.get("draft_markdown", "").lower()
    agent.tracker.set_rank("sample keyword", None)
    agent.record_roi(hours_saved=1.0, note="smoke", estimated=True)
    print("SMOKE OK", {{"business": st.get("business"), "topics": len(plan.get("topics") or [])}})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _readme_md(
    name: str,
    pkg: str,
    port: int,
    niche: str,
    goal: str,
    areas: list[str],
) -> str:
    areas_txt = ", ".join(areas) if areas else "not specified"
    return f"""# {name} — Bespoke SEO Agent

Generated by **Matrixly SEO-Bespoke** from your Business SEO Profile.

| | |
|--|--|
| **Business** | {name} |
| **Niche** | {niche} |
| **Primary goal** | {goal} |
| **Service areas** | {areas_txt} |
| **Package** | `{pkg}` |
| **Default port** | {port} |

This is **not** a thin wrapper around SEOForge. Modules are specialized to *your* services, locations, personas, and goals.

## Safety (non-negotiable)

- Never invent statistics, reviews, rankings, or guarantees
- Human approval required before publish
- Keyword ranks are owner-supplied only

## Quick start

```powershell
cd {pkg}
python -m venv .venv
.\\ .venv\\Scripts\\Activate.ps1
pip install -r requirements.txt
copy .env.example .env
python scripts/smoke_test.py
python -m agent.cli status
python -m agent.cli research
python -m agent.cli local
python -m agent.cli content --topic "your service"
python -m agent.cli serve
```

| URL | Purpose |
|-----|---------|
| http://localhost:{port}/v1/health | Health |
| http://localhost:{port}/docs | OpenAPI |

## What each module does

1. **Research planner** — topics & keyword *directions* from your quiz
2. **Brand voice** — tone locked to your unique value
3. **Local SEO** — GBP checklist, location outlines, review *templates*
4. **Content engine** — briefs + draft skeletons for your services
5. **Keyword tracker** — ranks only when you enter them
6. **ROI cards** — hours / leads / revenue you report

## Re-customize

Re-run the SEO-Bespoke quiz in the Matrixly dashboard to regenerate an updated package.
"""
