"""Daily email brief generation and delivery."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Protocol

from .config import SUMMARIES_DIR
from .llm import chat, grok_available
from .triage import TriageItem, triage_inbox, triage_report


class SupportsSummary(Protocol):
    def list_messages(
        self,
        query: str = "is:unread",
        max_results: int = 40,
        label_ids: list[str] | None = None,
    ) -> list[dict]: ...

    def get_message(self, message_id: str, format: str = "full") -> Any: ...

    def send_email(self, to: str, subject: str, body_text: str) -> dict: ...

    def fetch_inbox(
        self,
        max_results: int = 40,
        unread_only: bool = True,
        extra_query: str = "",
    ) -> list: ...

    def ensure_label(self, name: str) -> str: ...

    def apply_labels(
        self,
        message_id: str,
        add: list[str] | None = None,
        remove: list[str] | None = None,
    ) -> None: ...


def _stats_block(items: list[TriageItem]) -> str:
    by_cat: dict[str, int] = {}
    for i in items:
        by_cat[i.category] = by_cat.get(i.category, 0) + 1
    lines = ["### Stats"]
    for k, v in sorted(by_cat.items(), key=lambda kv: -kv[1]):
        lines.append(f"- {k}: {v}")
    if not by_cat:
        lines.append("- No messages in window")
    return "\n".join(lines)


def build_daily_summary(
    client: SupportsSummary,
    cfg: dict[str, Any],
    *,
    apply_labels: bool = True,
    use_llm: bool = True,
) -> str:
    summary_cfg = cfg.get("summary") or {}
    lookback = int(summary_cfg.get("lookback_hours") or 24)
    account = cfg.get("account") or {}
    primary = account.get("primary_email") or "mailbox"

    hours = max(1, lookback)
    days = max(1, (hours + 23) // 24)
    q_extra = f"newer_than:{days}d"

    triage_cfg = dict(cfg.get("triage") or {})
    local_cfg = dict(cfg)
    local_cfg["triage"] = {**triage_cfg, "unread_only": False}

    gmail_cfg = cfg.get("gmail") or {}
    imap_cfg = cfg.get("imap") or {}
    max_n = int(imap_cfg.get("max_results") or gmail_cfg.get("max_results") or 40)

    refs = client.list_messages(query=f"in:inbox {q_extra}", max_results=max_n)

    items = triage_inbox(
        client,
        local_cfg,
        apply_labels=apply_labels,
        max_results=max_n,
        use_llm=use_llm,
    )

    now = datetime.now().astimezone()
    header = (
        f"# Daily Email Brief\n\n"
        f"**Mailbox:** {primary}\n"
        f"**Generated:** {now.strftime('%Y-%m-%d %H:%M %Z')}\n"
        f"**Window:** last ~{lookback}h · {len(items)} messages reviewed "
        f"({len(refs)} matched recent query)\n"
    )

    body = triage_report(items)
    if body.startswith("# Inbox Triage Report"):
        body = body.split("\n", 1)[-1].lstrip()

    narrative = ""
    if use_llm and grok_available(cfg) and items:
        try:
            compact = [
                {
                    "subject": i.message.get("subject"),
                    "from": i.message.get("from_email"),
                    "category": i.category,
                    "score": i.score,
                    "snippet": (i.message.get("snippet") or "")[:200],
                }
                for i in items[:30]
            ]
            system = (
                "You write crisp executive email briefs for a CEO of an AI agent marketplace "
                "(Matrixly.AI / Matrix Bazaar, Houston). "
                "3-6 bullets max. Call out true urgents and anything needing a reply today. "
                "No fluff."
            )
            narrative = chat(
                cfg,
                system,
                f"Summarize today's inbox:\n{compact}",
                temperature=0.2,
            ).strip()
        except Exception as exc:  # noqa: BLE001
            print(f"warn: narrative summary skipped: {exc}")

    parts = [header]
    if narrative:
        parts.extend(["## Executive snapshot", narrative, ""])
    parts.append(body)
    parts.append(_stats_block(items))
    parts.append("")
    parts.append(
        "_Generated by Matrixly Email Assistant · drafts only — nothing was sent on your behalf "
        "(except this self-addressed brief when delivery is enabled)._"
    )
    return "\n".join(parts)


def write_summary_file(text: str):
    SUMMARIES_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = SUMMARIES_DIR / f"brief-{stamp}.md"
    path.write_text(text, encoding="utf-8")
    return path


def deliver_summary(
    client: SupportsSummary,
    cfg: dict[str, Any],
    text: str,
    *,
    send_email: bool = True,
) -> dict[str, Any]:
    summary_cfg = cfg.get("summary") or {}
    out: dict[str, Any] = {}

    if summary_cfg.get("write_markdown", True):
        path = write_summary_file(text)
        out["markdown_path"] = str(path)

    if send_email:
        to = summary_cfg.get("deliver_to") or (cfg.get("account") or {}).get("primary_email")
        prefix = summary_cfg.get("subject_prefix") or "[Matrixly Email Brief]"
        day = datetime.now().strftime("%Y-%m-%d")
        subject = f"{prefix} {day}"
        sent = client.send_email(to=to, subject=subject, body_text=text)
        out["sent_message_id"] = sent.get("id")
        out["delivered_to"] = to
        out["subject"] = subject

    return out
