#!/usr/bin/env node
/**
 * Matrixly.ai CI build — assemble a clean static publish directory.
 *
 * This is NOT a bundler step (no Vite/Next). It copies only public site
 * assets into dist/ so Hostinger never receives agents/, .env, or tooling.
 */
import {
  cpSync,
  mkdirSync,
  rmSync,
  writeFileSync,
  readdirSync,
  existsSync,
  statSync,
  readFileSync,
} from "node:fs";
import { join, extname } from "node:path";

const ROOT = process.cwd();
const DIST = join(ROOT, "dist");

const HTML_ALLOW = new Set([
  "index.html",
  "agents.html",
  "products.html",
  "integrations.html",
  "email-assistant.html",
  "lead-qualifier.html",
  "crm-assistant.html",
  "shipping-assistant.html",
  "shipping-assistant-guide.html",
  "support-forge.html",
  "book-wise.html",
]);

const ASSET_EXTS = new Set([
  ".css",
  ".js",
  ".mjs",
  ".map",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".svg",
  ".ico",
  ".woff",
  ".woff2",
  ".ttf",
  ".eot",
  ".txt",
  ".xml",
  ".json",
  ".webmanifest",
]);

const ASSET_DIRS = ["assets", "css", "js", "images", "img", "fonts", "static", "public"];

console.log("▸ Build: Matrixly.ai → dist/\n");

rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

let copied = 0;

function copyFile(src, dest) {
  cpSync(src, dest);
  copied += 1;
  console.log(`  + ${dest.slice(ROOT.length + 1).replaceAll("\\", "/")}`);
}

// Core HTML pages
for (const name of HTML_ALLOW) {
  const src = join(ROOT, name);
  if (!existsSync(src)) {
    console.error(`  ✗ Missing page: ${name}`);
    process.exit(1);
  }
  copyFile(src, join(DIST, name));
}

// Optional root static assets (robots, favicon, sitemap, etc.)
// Never ship Node tooling / lockfiles into public_html.
const ROOT_SKIP = new Set([
  "package.json",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "deploy-meta.json",
]);
for (const name of readdirSync(ROOT)) {
  if (HTML_ALLOW.has(name) || ROOT_SKIP.has(name)) continue;
  if (name.startsWith(".")) continue;
  const src = join(ROOT, name);
  if (!statSync(src).isFile()) continue;
  const ext = extname(name).toLowerCase();
  if (ASSET_EXTS.has(ext) || name === "robots.txt" || name === "favicon.ico" || name === "sitemap.xml") {
    copyFile(src, join(DIST, name));
  }
}

// Optional asset directories if added later
for (const dir of ASSET_DIRS) {
  const src = join(ROOT, dir);
  if (existsSync(src) && statSync(src).isDirectory()) {
    const dest = join(DIST, dir);
    cpSync(src, dest, { recursive: true });
    console.log(`  + ${dir}/ (recursive)`);
    copied += 1;
  }
}

// Production .htaccess for Hostinger Apache
const htaccess = `# Matrixly.ai — Hostinger / Apache
# Generated by scripts/ci-build.mjs — do not edit on the server (redeploys overwrite).

Options -Indexes
ServerSignature Off

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Force HTTPS
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Pretty URLs: /agents → agents.html (optional)
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME}.html -f
  RewriteRule ^(.+)$ $1.html [L]
</IfModule>

<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "SAMEORIGIN"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  Header set Permissions-Policy "geolocation=(), microphone=(), camera=()"
</IfModule>

# Cache static assets lightly; HTML always revalidated
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/html "access plus 0 seconds"
  ExpiresByType text/css "access plus 7 days"
  ExpiresByType application/javascript "access plus 7 days"
  ExpiresByType image/png "access plus 30 days"
  ExpiresByType image/jpeg "access plus 30 days"
  ExpiresByType image/webp "access plus 30 days"
  ExpiresByType image/svg+xml "access plus 30 days"
  ExpiresByType font/woff2 "access plus 30 days"
</IfModule>
`;
writeFileSync(join(DIST, ".htaccess"), htaccess, "utf8");
console.log("  + dist/.htaccess");
copied += 1;

// Lightweight deploy stamp (not a secret)
const stamp = {
  site: "matrixly.ai",
  builtAt: new Date().toISOString(),
  pages: [...HTML_ALLOW],
  node: process.version,
};
writeFileSync(join(DIST, "deploy-meta.json"), JSON.stringify(stamp, null, 2) + "\n", "utf8");
console.log("  + dist/deploy-meta.json");
copied += 1;

// Safety: never ship env files
for (const bad of [".env", ".env.local", ".env.production"]) {
  if (existsSync(join(DIST, bad))) {
    console.error(`  ✗ Refusing to publish ${bad}`);
    process.exit(1);
  }
}

// Verify index
const index = readFileSync(join(DIST, "index.html"), "utf8");
if (!index.includes("Matrixly")) {
  console.error("  ✗ dist/index.html does not look like Matrixly site");
  process.exit(1);
}

console.log(`\n✔ Build complete — ${copied} item(s) in dist/\n`);
